In [1]:
import numpy as np 
import pandas as pd

<ipython-input-1-f20def6a2be1>:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
>>> import warnings
>>> warnings.filterwarnings("ignore", "\nPyarrow", DeprecationWarning)
>>> import pandas ##this to reslove the problem of pandas

In [12]:
a=np.random.randint(low=1,high=100,size=(4,4,4))

In [13]:
a

array([[[47, 74, 38, 42],
        [88, 72,  6, 69],
        [ 2, 82, 60, 52],
        [83, 29, 11, 11]],

       [[46, 84, 63, 68],
        [18, 22, 98, 43],
        [15,  6, 14, 57],
        [35, 61, 11, 65]],

       [[59,  1, 97, 74],
        [52, 65, 39,  9],
        [64, 67, 42, 39],
        [59, 42, 88, 46]],

       [[28, 43, 69, 88],
        [88, 24, 39, 18],
        [47, 52, 88, 36],
        [83, 14, 71, 74]]])

In [21]:
m=np.mean(a)

In [16]:
m

49.640625

In [17]:
n=np.std(a)

In [18]:
n

26.712805442509683

In [19]:
j=(a-m)/n

In [20]:
j

array([[[-0.0988524 ,  0.91189879, -0.43576947, -0.28602855],
        [ 1.435992  ,  0.83702833, -1.63369681,  0.72472264],
        [-1.78343773,  1.21138063,  0.38780558,  0.08832374],
        [ 1.24881586, -0.77268653, -1.44652066, -1.44652066]],

       [[-0.13628763,  1.28625109,  0.50011127,  0.68728742],
        [-1.18447406, -1.03473314,  1.8103443 , -0.24859332],
        [-1.29677974, -1.63369681, -1.33421497,  0.27549989],
        [-0.54807516,  0.42524081, -1.44652066,  0.57498173]],

       [[ 0.35037035, -1.82087296,  1.77290907,  0.91189879],
        [ 0.08832374,  0.57498173, -0.39833424, -1.52139112],
        [ 0.5375465 ,  0.64985219, -0.28602855, -0.39833424],
        [ 0.35037035, -0.28602855,  1.435992  , -0.13628763]],

       [[-0.81012176, -0.24859332,  0.72472264,  1.435992  ],
        [ 1.435992  , -0.95986268, -0.39833424, -1.18447406],
        [-0.0988524 ,  0.08832374,  1.435992  , -0.51063993],
        [ 1.24881586, -1.33421497,  0.7995931 ,  0.91189879]]])

In [22]:
import numpy as np 
import pandas as pd


In [23]:
>>> import warnings
>>> warnings.filterwarnings("ignore", "\nPyarrow", DeprecationWarning)
>>> import pandas

In [24]:
from numpy.random import randn

In [25]:
np.random.seed(101)

In [26]:
d=pd.DataFrame(randn(3,3),['A','B','C'],['W','X','Y'])

In [27]:
d

W         X         Y
A  2.706850  0.628133  0.907969
B  0.503826  0.651118 -0.319318
C -0.848077  0.605965 -2.018168

In [34]:
df=pd.DataFrame({'A':['1','2',np.nan],
                'B':['2',np.nan,np.nan],
                'C':['4',np.nan,np.nan]},
                index=[0,1,2]
                 )

In [29]:
df

A    B    C
0    1    2    4
1    2  NaN  NaN
2  NaN  NaN  NaN

In [35]:
df.fillna(value='fill value')

A           B           C
0           1           2           4
1           2  fill value  fill value
2  fill value  fill value  fill value

In [36]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2]

In [37]:
df.dropna()

A  B  C
0  1  2  4

In [38]:
df.dropna(axis=1,thresh=2)

A
0    1
1    2
2  NaN

In [39]:
df.dropna(axis=0,thresh=2)

A  B  C
0  1  2  4

In [40]:
df.fillna(value='fill value')

A           B           C
0           1           2           4
1           2  fill value  fill value
2  fill value  fill value  fill value

In [45]:
import numpy as np 
import pandas as pd

In [46]:
>>> import warnings
>>> warnings.filterwarnings("ignore", "\nPyarrow", DeprecationWarning)
>>> import pandas ##this to reslove the problem of pandas

In [50]:
d={'A':[1,np.nan,3],
  'B':[2,np.nan,np.nan],
  'C':[4,5,6]}

In [51]:
d=pd.DataFrame(d)

In [52]:
d

A    B  C
0  1.0  2.0  4
1  NaN  NaN  5
2  3.0  NaN  6

In [53]:
d.dropna()

A    B  C
0  1.0  2.0  4

In [54]:
d.dropna(axis=1)

C
0  4
1  5
2  6

In [56]:
d.fillna(value='Fill value')

A           B  C
0         1.0         2.0  4
1  Fill value  Fill value  5
2         3.0  Fill value  6

In [57]:
d['A'].fillna(value=d['A'].mean())

0    1.0
1    2.0
2    3.0
Name: A, dtype: float64

In [58]:
d['B'].fillna(value=d['B'].mean())

0    2.0
1    2.0
2    2.0
Name: B, dtype: float64

In [62]:
d['A'].sort_values()

0    1.0
2    3.0
1    NaN
Name: A, dtype: float64

In [63]:
d['B'].sort_values()

0    2.0
1    NaN
2    NaN
Name: B, dtype: float64

In [64]:
import numpy as np 
import pandas as pd

In [67]:
a1=np.random.randint(low=1,high=10,size=(4,4))

In [68]:
a2=np.random.randint(low=1,high=10,size=(4,4))

In [69]:
dot_product = np.dot(a1,a2)


In [70]:
determinant= np.linalg.det(dot_product)


In [71]:
a1

array([[2, 4, 9, 4],
       [4, 3, 9, 4],
       [8, 1, 8, 9],
       [5, 4, 4, 8]])

In [72]:
a2

array([[5, 9, 8, 7],
       [5, 3, 8, 8],
       [8, 1, 5, 2],
       [9, 4, 2, 9]])

In [73]:
dot_product

array([[138,  55, 101, 100],
       [143,  70, 109, 106],
       [190, 119, 130, 161],
       [149,  93, 108, 147]])

In [74]:
determinant

-1047795.0000000001

In [75]:
import numpy as np
import pandas as pd

In [76]:
d={'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
     'Person':['Sam','Avan','Ram','Anu','Vedu','Tanu'],
     'Sales':[200,100,300,124,243,340]}

In [77]:
d

{'Company': ['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'],
 'Person': ['Sam', 'Avan', 'Ram', 'Anu', 'Vedu', 'Tanu'],
 'Sales': [200, 100, 300, 124, 243, 340]}

In [78]:
df=pd.DataFrame(d)

In [79]:
df

Company Person  Sales
0    GOOG    Sam    200
1    GOOG   Avan    100
2    MSFT    Ram    300
3    MSFT    Anu    124
4      FB   Vedu    243
5      FB   Tanu    340

In [80]:
bycom=df.groupby('Company')

In [82]:
bycom

In [83]:
bycom.sum()

Person  Sales
Company                 
FB       VeduTanu    583
GOOG      SamAvan    300
MSFT       RamAnu    424

In [84]:
import numpy as np 
arr_2D = np.array([[0, 1, 1], [1, 0, 1], [1, 1, 0]])

In [85]:
arr_2D

array([[0, 1, 1],
       [1, 0, 1],
       [1, 1, 0]])

In [86]:
import numpy as np 
arr_1D = np.array([2,4,6,8])

In [87]:
arr_1D

array([2, 4, 6, 8])

In [88]:
import numpy as np
arr_3D = np.array([[[0, 1, 1], [1, 0, 1], [1, 1, 0]]])

In [89]:
arr_3D

array([[[0, 1, 1],
        [1, 0, 1],
        [1, 1, 0]]])

In [90]:
left=pd.DataFrame({'key1':['K0','K1','K2','K3'],
                  'A':['A0','A1','A2','A3'],
                  'B':['B0','B1','B2','B3']})

In [91]:
right=pd.DataFrame({'key1':['K0','K1','K2','K3'],
                  'A':['A0','A1','A2','A3'],
                  'B':['B0','B1','B2','B3']})

In [92]:
left

key1   A   B
0   K0  A0  B0
1   K1  A1  B1
2   K2  A2  B2
3   K3  A3  B3

In [93]:
right

key1   A   B
0   K0  A0  B0
1   K1  A1  B1
2   K2  A2  B2
3   K3  A3  B3

In [95]:
pd.merge(left,right,how='inner',on='key1')

key1 A_x B_x A_y B_y
0   K0  A0  B0  A0  B0
1   K1  A1  B1  A1  B1
2   K2  A2  B2  A2  B2
3   K3  A3  B3  A3  B3